name: WakeLeanCloud
on:
  schedule:
    - cron: '*/29 23-23 * * ?'
    - cron: '*/29 0-15 * * ?'
  workflow_dispatch:
jobs:
  build:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - name: use Node.js 10.x
         uses: actions/setup-node@v1
         with:
           node-version: 10.x
       - name: npm install and env
         run: |
           sudo npm install https async dotenv
           touch .env
           echo SITE="${{ secrets.SITE }}" > .env
       - name: run
         run: |
           node run.js

