name: WakeLeanCloud
on:
  schedule:
    - cron: '*/20 23-23 * * *'
    - cron: '*/20 0-15 * * *'
  workflow_dispatch:
jobs:
  build:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - name: use Node.js 10.x
         uses: actions/setup-node@v1
         with:
           node-version: 10.x
       - name: npm install and env
         run: |
           sudo npm install https async dotenv
           echo SITE="${{ secrets.SITE }}" > .env
           echo SITE="${{ secrets.SITE2 }}" >> .env
           echo SITE="${{ secrets.SITE3 }}" >> .env
       - name: run
         run: |
           node test.js

